# Generated by Django 4.0.5 on 2022-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.BigIntegerField(max_length=20)),
                ('Character', models.BigIntegerField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(default=0)),
            ],
            options={
                'db_table': 'app_anime',
            },
        ),
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'app_anime_type',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('profile_pic', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('verification_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=0)),
                ('update_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
